consumer:
    resource: "@ConsumerBundle/Resources/config/routing.yml"
    prefix:   /

shopkeeper:
    resource: "@ShopkeeperBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
