ShopkeeperBundle\Entity\Project:
    type: entity
    table: shopkeeper_projects
    repositoryClass: ShopkeeperBundle\Entity\ProjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 180
        description:
            type: string
            length: 500
        owner_id:
            type: integer
        supplier_id:
            type: integer
        postedAt:
            name: created_at
            type: datetime
        expire_at:
            type: datetime
    lifecycleCallbacks: {  }
